// Shared content for the P.R.E.S.S. expertise pages and the selected-work
// case studies. Sourced from the TPC website sitemap (services) and the
// PRESS DECK client deck (scope, outcomes, metrics, exhibits).

export const PILLARS = [
  {
    slug: 'presence',
    letter: 'P',
    num: '01',
    name: 'Presence & Branding',
    promise: 'Build a brand people notice, trust, and remember.',
    intro:
      'We create the complete foundation of your brand — from positioning and messaging to every customer touchpoint — so your business looks premium, communicates clearly, and stands out in a crowded market.',
    services: [
      { t: 'Brand Strategy', d: 'A clear brand vision, market positioning, target audience, competitive advantage, and long-term growth roadmap.' },
      { t: 'Brand Positioning', d: 'Defining what makes your brand different and creating a unique space in the minds of your audience.' },
      { t: 'Brand Identity Design', d: 'Creating or refining your visual identity — logos, typography, colour systems, and overall brand aesthetics.' },
      { t: 'Personal Branding', d: 'Influential personal brands for founders, CEOs, doctors, creators, and industry leaders.' },
      { t: 'Brand Messaging', d: 'Your brand voice, communication style, key messaging, value proposition, and taglines.' },
      { t: 'Brand Storytelling', d: 'Compelling brand narratives that create emotional connections with your audience.' },
      { t: 'Brand Guidelines', d: 'Comprehensive guideline documents that keep every touchpoint consistent.' },
      { t: 'Visual Communication Design', d: 'Creative design systems and visual assets that strengthen brand recognition.' },
      { t: 'Website Strategy', d: 'Structure, user journey, content flow, and conversion strategy for your website.' },
      { t: 'Website Design & Development', d: 'Responsive, SEO-friendly, conversion-focused business websites.' },
      { t: 'Company Profile & Portfolio Design', d: 'Professional company profiles, brochures, portfolios, and capability decks.' },
      { t: 'Pitch Deck & Investor Presentation Design', d: 'Persuasive startup pitch decks, investor presentations, and business proposals.' },
      { t: 'Packaging Design & Consultation', d: 'Packaging aligned with your brand that improves shelf presence and customer experience.' },
      { t: 'Sales & Marketing Collateral Design', d: 'Brochures, flyers, catalogues, standees, merchandise, and every supporting brand asset.' },
    ],
    cases: ['throve', 'pratap-steels', 'alignllife'],
  },
  {
    slug: 'reach',
    letter: 'R',
    num: '02',
    name: 'Reach Engineering',
    promise: 'Get your brand in front of the right audience, consistently.',
    intro:
      "Growth doesn't happen by chance. We design multi-channel visibility systems that increase awareness, generate demand, and put your business where your customers already are.",
    services: [
      { t: 'Organic Social Media Marketing', d: 'A consistent presence through content strategy, creation, community engagement, and platform management.' },
      { t: 'Paid Advertising Strategy', d: 'Performance-driven campaigns planned and managed for reach, leads, sales, and ROI.' },
      { t: 'Meta Ads Management', d: 'Creating, managing, and optimizing Facebook and Instagram advertising campaigns.' },
      { t: 'Google Ads Management', d: 'High-converting Google Search, Display, YouTube, and Performance Max campaigns.' },
      { t: 'Search Engine Optimization (SEO)', d: 'On-page and technical SEO, keyword strategy, and content optimization for better rankings.' },
      { t: 'Google Business Profile Management', d: 'Optimized profiles that improve local visibility, customer trust, and search rankings.' },
      { t: 'Influencer Marketing', d: 'Identifying, onboarding, and managing creators who build credibility and expand reach.' },
      { t: 'Public Relations & Media Outreach', d: 'PR strategies, press releases, and media coverage across publications and digital media.' },
      { t: 'Brand Collaborations & Partnerships', d: 'Strategic collaborations that unlock new audiences and business opportunities.' },
      { t: 'Community Building', d: 'Engaged online and offline communities that strengthen relationships and loyalty.' },
      { t: 'Referral Marketing', d: 'Customer referral programs that encourage word-of-mouth growth and repeat business.' },
      { t: 'Email Marketing', d: 'Campaigns for customer engagement, lead nurturing, product launches, and retention.' },
      { t: 'WhatsApp Marketing', d: 'Customer communication, lead nurturing, promotions, and automated engagement.' },
      { t: 'Marketplace Visibility', d: 'Optimized listings and strategic positioning across e-commerce marketplaces.' },
      { t: 'Local & Offline Marketing', d: 'Local partnerships, retail marketing, society activations, exhibitions, and on-ground campaigns.' },
    ],
    cases: ['belief-salon', 'daigo', 'furry-essentials'],
  },
  {
    slug: 'experience',
    letter: 'E',
    num: '03',
    name: 'Experience & Engagement',
    promise: 'Create memorable brand experiences that build lasting customer relationships.',
    intro:
      'Marketing goes beyond getting attention — it is about meaningful interactions that keep customers engaged, encourage loyalty, and turn one-time buyers into long-term advocates. We design online and offline experiences that strengthen every stage of the customer journey.',
    services: [
      { t: 'Marketing Campaign Strategy', d: 'Integrated campaigns aligned with business goals across digital and offline channels.' },
      { t: 'Product Launch Campaigns', d: 'Launch strategies for new products, services, stores, or brands that maximize market impact.' },
      { t: 'Event Marketing', d: 'Corporate events, brand launches, workshops, conferences, and promotional activities.' },
      { t: 'Exhibition & Trade Show Marketing', d: 'Exhibition strategies, booth branding, visitor engagement, and lead generation for expos.' },
      { t: 'Brand Activations', d: 'On-ground activations, retail experiences, mall and college campaigns, and experiential marketing.' },
      { t: 'Customer Experience Strategy', d: 'Journeys and touchpoints designed to improve satisfaction, engagement, and perception.' },
      { t: 'Customer Journey Mapping', d: 'Understanding and optimizing every interaction to improve conversions and retention.' },
      { t: 'Community Building & Engagement', d: 'Active communities built through engagement initiatives, events, and communication.' },
      { t: 'Customer Retention & Loyalty Programs', d: 'Loyalty programs, membership strategies, and retention campaigns that raise lifetime value.' },
      { t: 'CRM & Customer Communication', d: 'Email, WhatsApp, SMS, and CRM journeys for nurturing, engagement, and retention.' },
      { t: 'Seasonal & Promotional Campaigns', d: 'Festive campaigns, seasonal promotions, and occasion-based marketing initiatives.' },
      { t: 'Customer Feedback & Reputation Management', d: 'Systems that collect feedback, improve experiences, and manage online reviews.' },
    ],
    cases: ['furry-essentials', 'daigo', 'belief-salon'],
  },
  {
    slug: 'systems',
    letter: 'S',
    num: '04',
    name: 'Strategic Marketing Systems',
    promise: 'Marketing backed by data, not guesswork.',
    intro:
      'Every successful brand needs a roadmap. We build scalable marketing systems that align business goals with execution and ensure every activity contributes to measurable growth.',
    services: [
      { t: 'Marketing Strategy', d: 'Comprehensive roadmaps aligned with your business goals, audience, and growth objectives.' },
      { t: 'Business Growth Strategy', d: 'Opportunities to scale through market expansion, acquisition, and revenue initiatives.' },
      { t: 'Go-to-Market (GTM) Strategy', d: 'Successful launches through positioning, pricing, distribution, and marketing execution.' },
      { t: 'Integrated Marketing Communication', d: 'Cohesive strategies that keep messaging consistent across digital, offline, PR, and events.' },
      { t: 'Marketing Consulting', d: 'Expert guidance on branding, marketing, growth, and business development.' },
      { t: 'Fractional CMO Services', d: 'Your outsourced Chief Marketing Officer — leading strategy, overseeing execution, mentoring teams.' },
      { t: 'Product Marketing Strategy', d: 'Positioning products through research, messaging, pricing support, and launch planning.' },
      { t: 'Pricing Strategy Consultation', d: 'Competitive pricing models based on market positioning and customer perception.' },
      { t: 'Market Research', d: 'Industry, market, and customer research with opportunity mapping for informed decisions.' },
      { t: 'Competitor Analysis', d: "Evaluating competitors' branding, products, pricing, and digital presence for your advantage." },
      { t: 'Consumer Research & Insights', d: 'Customer behaviour, buying patterns, preferences, and pain points decoded.' },
      { t: 'Campaign Planning', d: 'Integrated campaigns with clear objectives, timelines, budgets, and performance metrics.' },
      { t: 'Marketing Audit', d: 'A review of your existing branding, marketing, and performance to find growth opportunities.' },
      { t: 'Sales Funnel Strategy', d: 'Acquisition funnels that guide prospects from awareness to conversion.' },
      { t: 'Lead Generation Strategy', d: 'Systems that attract, qualify, nurture, and convert high-quality leads.' },
      { t: 'Marketing Analytics & Performance Reporting', d: 'Campaign performance, customer behaviour, and KPIs tracked for data-driven decisions.' },
      { t: 'Marketing Automation Strategy', d: 'Automation for lead nurturing, CRM workflows, email and WhatsApp journeys, and segmentation.' },
    ],
    cases: ['janvi-chitalia', 'one-essence', 'alignllife', 'daigo'],
  },
  {
    slug: 'storytelling',
    letter: 'S',
    num: '05',
    name: 'Storytelling & Social',
    promise: 'Create content that captures attention, builds trust, and drives meaningful results.',
    intro:
      'Content is the voice of your brand. We develop strategic, high-quality content that educates, entertains, and converts across every platform — from social media and video to creative campaigns and brand storytelling.',
    services: [
      { t: 'Social Media Strategy', d: 'Platform-specific strategies tailored to your goals, audience, and brand positioning.' },
      { t: 'Social Media Management', d: 'Planning, publishing, community management, and performance tracking.' },
      { t: 'Content Marketing Strategy', d: 'Content plans that support awareness, engagement, lead generation, and retention.' },
      { t: 'Content Planning & Calendars', d: 'Monthly calendars aligned with campaigns, trends, launches, and business objectives.' },
      { t: 'Short-form Video Strategy', d: 'High-performing Reels, Shorts, and vertical video designed for reach and engagement.' },
      { t: 'Creative Direction', d: 'Creative concepts, campaign ideas, visual direction, and content themes.' },
      { t: 'Copywriting', d: 'Website copy, ad copy, social captions, marketing materials, and brand communications.' },
      { t: 'Scriptwriting', d: 'Engaging scripts for Reels, advertisements, corporate videos, podcasts, and campaigns.' },
      { t: 'UGC Strategy', d: 'Creator-led and customer-generated content strategies that build trust and authenticity.' },
      { t: 'Photography & Videography Direction', d: 'Shoots, mood boards, shot lists, and visual storytelling for professional production.' },
      { t: 'Ad Creative Strategy', d: 'High-converting ad creatives for Meta, Google, YouTube, and digital platforms.' },
      { t: 'Graphic Design & Brand Creatives', d: 'Social creatives, marketing collateral, digital assets, and presentations on-brand.' },
      { t: 'Content Trend Research', d: 'Industry trends, platform updates, and emerging opportunities to keep your brand relevant.' },
      { t: 'SEO Content Marketing', d: 'SEO-driven website content, blogs, and landing pages that grow organic traffic.' },
      { t: 'Blog & Article Writing', d: 'Keyword-optimized articles that establish thought leadership and discoverability.' },
      { t: 'Email Newsletter Content', d: 'Newsletters that nurture leads, retain customers, and strengthen relationships.' },
      { t: 'Podcast & Long-form Content Strategy', d: 'Podcasts, YouTube, webinars, and long-form content that build authority and trust.' },
    ],
    cases: ['furry-essentials', 'belief-salon', 'throve'],
  },
];

// The studio's working roadmap — from The Press Edit.
export const ROADMAP = [
  { t: 'Discovery call', d: 'A focused decoding call to understand your brand, challenges, and growth intent.' },
  { t: 'Strategic intake', d: 'A structured brand form that gathers clarity on goals, positioning, audience, and internal gaps.' },
  { t: 'Internal brand audit', d: 'We evaluate your existing presence, communication, and growth potential.' },
  { t: 'Strategy, then the press', d: 'A tailored plan — then consistent execution across every touchpoint that matters.' },
];

// Selected proof — 7 engagements from the client deck, set in full.
export const CASES = [
  {
    slug: 'furry-essentials',
    client: 'Furry Essentials',
    industry: 'Pet Care',
    engagement: 'Brand Positioning · Social Media · Community',
    result: '55,070 views and 2,197 interactions in thirty days — a pet-care brand turned community.',
    summary:
      'A complete social engagement for a pet-care brand: re-branding, a structured content ecosystem for pet parents, and community management that turned followers into daily enquiries.',
    scope: [
      'Social media management', 'Content planning & calendars', 'Re-branding',
      'Reels & content strategy', 'Community management', 'Script writing',
      'Shooting', 'Offline marketing', 'Campaign planning', 'Performance optimization',
    ],
    outcomes: [
      'Established a consistent premium brand identity.',
      'Built a structured content ecosystem for pet parents.',
      'Increased engagement through educational and relatable content.',
      'Strengthened brand recall with recurring content formats.',
      'Positioned the brand as a trusted pet-care expert.',
      'Supported awareness, community growth, and enquiry generation.',
    ],
    metrics: [
      { v: '55,070', l: 'views in 30 days' },
      { v: '2,197', l: 'interactions in 30 days' },
      { v: '91%', l: 'of views from non-followers' },
    ],
    hero: { src: '/work/furry-essentials/hero.jpg', w: 1200, h: 628, cap: 'Brand maturity across the engagement' },
    exhibits: [
      { src: '/work/furry-essentials/01.jpg', w: 369, h: 800, cap: 'Instagram views — 30 days' },
      { src: '/work/furry-essentials/02.jpg', w: 369, h: 800, cap: 'Interactions — 30 days' },
      { src: '/work/furry-essentials/03.jpg', w: 426, h: 923, cap: 'Community DMs & booking enquiries' },
      { src: '/work/furry-essentials/04.jpg', w: 864, h: 584, cap: 'Brand maturity journey across the engagement' },
    ],
  },
  {
    slug: 'belief-salon',
    client: 'Belief Salon',
    industry: 'Beauty',
    engagement: 'Social Media Marketing · Offline Brand Strategy',
    result: '286,512 views in thirty days; accounts reached up 1,910%.',
    summary:
      'Instagram-focused marketing for a local salon — content creation, post design, and performance optimization, backed by offline pamphlet distribution for on-ground acquisition.',
    scope: [
      'Instagram-focused social media marketing',
      'Content creation, post design & performance optimization',
      'Selected post promotion for visibility and reach',
      'Offline distribution templates for local marketing',
    ],
    outcomes: [
      'Strong Instagram performance with high reach, views, and engagement.',
      'A significant rise in inbound messages, interest, and awareness.',
      'Boosted content improved visibility among the target local audience.',
      'Offline pamphlet designs supported on-ground distribution and recall.',
    ],
    metrics: [
      { v: '286,512', l: 'views in 30 days' },
      { v: '170,165', l: 'accounts reached' },
      { v: '+1,910%', l: 'growth in accounts reached' },
    ],
    hero: { src: '/work/belief-salon/hero.jpg', w: 1200, h: 628, cap: 'Instagram audience — followers vs non-followers' },
    exhibits: [
      { src: '/work/belief-salon/01.jpg', w: 516, h: 916, cap: 'Instagram views — 30 days' },
      { src: '/work/belief-salon/02.jpg', w: 516, h: 916, cap: 'Post insights — views over time' },
    ],
  },
  {
    slug: 'daigo',
    client: 'Daigo',
    industry: 'FMCG · Food & Beverage',
    engagement: 'Integrated Brand & Marketing Management',
    result: '92.6% of views now come from non-followers — new audiences on tap.',
    summary:
      'Positioned Daigo as the convenient buttermilk for Indians travelling and living abroad — a culturally relevant consumer need — then built the marketing ecosystem around it, across digital and offline touchpoints.',
    scope: [
      'Brand strategy & consultation', 'Brand positioning', 'Social media strategy & management',
      'Performance marketing (Meta ads)', 'Content strategy & planning', 'Community management',
      'Photoshoot direction & creative assistance', 'Event marketing & execution',
      'Exhibition & booth planning', 'Marketing collateral', 'Campaign ideation', 'End-to-end brand management',
    ],
    outcomes: [
      'Established Daigo as a convenient buttermilk solution around a culturally relevant need.',
      'Built a cohesive marketing ecosystem across digital and offline touchpoints.',
      'Strengthened brand visibility, customer engagement, and purchase consideration.',
    ],
    metrics: [
      { v: '58,971', l: 'views in 90 days' },
      { v: '92.6%', l: 'of views from non-followers' },
      { v: '+33%', l: 'reels & post views month-on-month' },
    ],
    hero: { src: '/work/daigo/hero.jpg', w: 1200, h: 628, cap: 'Instagram analytics — 58,971 views' },
    exhibits: [
      { src: '/work/daigo/01.jpg', w: 720, h: 900, cap: 'Instagram analytics — 90 days' },
      { src: '/work/daigo/02.jpg', w: 864, h: 1080, cap: 'Audience shift — before & after' },
      { src: '/work/daigo/03.jpg', w: 443, h: 960, cap: 'Instagram grid' },
      { src: '/work/daigo/04.jpg', w: 360, h: 640, cap: 'Content production, behind the scenes' },
    ],
  },
  {
    slug: 'alignllife',
    client: 'Alignllife',
    industry: 'Healthcare',
    engagement: 'Brand Development',
    result: 'First sale within five posts of launch — relatability as the growth engine.',
    summary:
      'An early-stage brand built from the foundation: strategy, identity, communication, and integrated execution. Relatability-led positioning shaped every piece of communication — and drove sales from the first week of content.',
    scope: [
      'Brand planning, category understanding & competitor analysis',
      'Brand strategy, positioning & narrative direction',
      'Logo refinement, visual direction & brand archetypes',
      'Brand voice & messaging system',
      'Social media & content strategy — pillars, storytelling, thematic structure',
      'Creative direction for shoots, video content & AI-assisted visuals',
      'Offline branding — flyers & printed materials',
      'Marketing planning across audience segments, including U.S. positioning',
    ],
    outcomes: [
      'Relatability-led positioning that directly shapes communication and audience connection.',
      'Sales within the first 5 posts, driven by relatable storytelling.',
      'Two more sales from Instagram within 7–8 posts — early organic traction.',
      'Positioning strengthened through relatability as the core driver of engagement and conversions.',
    ],
    metrics: [
      { v: '5 posts', l: 'to the first sale' },
      { v: '7–8 posts', l: 'to two more Instagram sales' },
      { v: '0 → 1', l: 'brand system built from the foundation' },
    ],
    hero: { src: '/work/alignllife/hero.jpg', w: 1200, h: 628, cap: 'Consistent alignment across every touchpoint' },
    exhibits: [
      { src: '/work/alignllife/01.jpg', w: 768, h: 512, cap: 'Logo story — built on alignment' },
      { src: '/work/alignllife/02.jpg', w: 669, h: 377, cap: 'Brand application — every touchpoint' },
      { src: '/work/alignllife/03.jpg', w: 443, h: 960, cap: 'Instagram grid' },
      { src: '/work/alignllife/04.jpg', w: 681, h: 1384, cap: 'Clinic poster — leading the future of chiropractic care' },
    ],
  },
  {
    slug: 'throve',
    client: 'Throve',
    industry: 'Apparel',
    engagement: 'End-to-End Brand Development',
    result: 'A premium apparel brand built from the ground up — strategy to shelf.',
    summary:
      'THROVE was a complete brand-building exercise, not a visual identity project: strategy, positioning, identity, packaging, customer experience, launch planning, and marketing foundations — everything a premium market entry demands.',
    scope: [
      'Brand positioning, personality & story',
      'Logo design, colour system, typography & brand book',
      'Premium unboxing, packaging & brand touchpoints',
      'Material sourcing, vendor coordination & production assistance',
      'Launch strategy & go-to-market plan',
      'Social media strategy, content calendar & campaign planning',
      'Photoshoot planning, creative direction & website content',
    ],
    outcomes: [
      'A brand that competes in a premium market with a distinct personality.',
      'A consistent customer experience across every physical and digital touchpoint.',
      'A scalable brand system — from logo construction to packaging direction.',
    ],
    metrics: [],
    hero: { src: '/work/throve/hero.jpg', w: 1200, h: 628, cap: 'Logo story & brand system' },
    exhibits: [
      { src: '/work/throve/01.jpg', w: 1031, h: 550, cap: 'Logo story & construction' },
      { src: '/work/throve/02.jpg', w: 421, h: 337, cap: 'Hang tags & packaging touchpoints' },
      { src: '/work/throve/03.jpg', w: 502, h: 502, cap: 'Lifestyle campaign' },
      { src: '/work/throve/04.jpg', w: 391, h: 480, cap: 'Type specimens' },
    ],
  },
  {
    slug: 'janvi-chitalia',
    client: 'Janvi Chitalia',
    industry: 'Health & Nutrition',
    engagement: '360° Brand Building · Outsourced CMO',
    result: 'An outsourced-CMO engagement across every online and offline touchpoint.',
    summary:
      "Acted as the brand's outsourced CMO — leading strategy, execution, creative, marketing, customer experience, and growth across all digital touchpoints for a gut-health coach and functional nutritionist.",
    scope: [
      'Brand strategy, positioning & marketing strategy',
      'Social media strategy, management & content production',
      'Creative direction, photoshoots & reel production',
      'Performance marketing (Meta ads) & ad creatives',
      'Website strategy, content & SEO',
      'Recipe book development & digital product creation',
      'Voucher & coupon systems, customer journey design',
      'PR, podcast outreach & influencer collaboration',
      'Email & WhatsApp marketing, sales funnel planning',
    ],
    outcomes: [
      'A premium, cohesive brand identity across all customer touchpoints.',
      'A complete digital ecosystem — social, website, digital products, customer experience.',
      'Increased visibility through strategic content, paid advertising, PR, and podcasts.',
      'The founder positioned as an industry expert through authority-building initiatives.',
      'End-to-end brand management with consistency across every touchpoint.',
    ],
    metrics: [],
    hero: { src: '/work/janvi-chitalia/hero.jpg', w: 1200, h: 628, cap: 'The founder as category authority' },
    exhibits: [
      { src: '/work/janvi-chitalia/01.jpg', w: 425, h: 600, cap: 'Brand cover' },
      { src: '/work/janvi-chitalia/02.jpg', w: 432, h: 432, cap: 'E-book launch creative' },
      { src: '/work/janvi-chitalia/03.jpg', w: 256, h: 400, cap: 'Recipe cookbook' },
      { src: '/work/janvi-chitalia/04.jpg', w: 547, h: 308, cap: 'Authority building — speaking & coaching' },
    ],
  },
  {
    slug: 'pratap-steels',
    client: 'Pratap Steels',
    industry: 'Steel · B2B',
    engagement: 'Brand Identity & Corporate Assets',
    result: 'A 1980s steel business re-pressed into a modern B2B brand.',
    summary:
      'A cohesive corporate identity for a legacy steel re-roller: visual language, website, product and industrial photography, and the full set of sales-enablement assets — unified across digital and print.',
    scope: [
      'Corporate identity system — colours, typography & visual language',
      'Website design & development',
      'Product & industrial photography',
      'Corporate brochure & product catalogue design',
      'Hoarding, banner & event branding',
      'Print collateral & brand asset management',
    ],
    outcomes: [
      'A cohesive corporate identity across digital and print touchpoints.',
      'A professional marketing ecosystem that strengthened brand credibility.',
      'Enhanced product presentation and improved sales enablement.',
      'A unified online and offline presence with increased brand visibility.',
    ],
    metrics: [],
    hero: { src: '/work/pratap-steels/hero.jpg', w: 1200, h: 628, cap: "India's premier stainless & alloy stockist" },
    exhibits: [
      { src: '/work/pratap-steels/01.jpg', w: 1134, h: 567, cap: 'Trade banner — stainless & alloy stockist' },
      { src: '/work/pratap-steels/02.jpg', w: 959, h: 493, cap: 'Corporate website' },
      { src: '/work/pratap-steels/03.jpg', w: 566, h: 800, cap: 'Brand brochure — strength that drives industry' },
      { src: '/work/pratap-steels/04.jpg', w: 432, h: 540, cap: 'Metal business card' },
    ],
  },
  {
    slug: 'one-essence',
    client: 'One Essence',
    industry: 'Nutrition',
    engagement: 'Book Development',
    result: 'A US-exclusive clinical nutrition ecosystem — structured book, programs, and premium pricing.',
    summary:
      'A US-exclusive clinical nutrition product ecosystem for NRI / HNI-NRI individuals in the United States — a structured digital nutrition book that turns the founder’s clinical expertise into diet plans, programs, and a clear premium product hierarchy.',
    scope: [
      'US-exclusive clinical nutrition product ecosystem',
      'Structured digital nutrition book, aligned to clinical & premium positioning',
      'Diet plans, nutrition programs & services into one ecosystem',
      'Modular content framework for future recipe & nutrition expansion',
      'Clear, premium product hierarchy for scalability',
      'Content Structure System (CSS) for consistent brand communication',
      'Premium USD-priced positioning, exclusive to the US market',
    ],
    outcomes: [
      'Founder-collaborative system design — clinical expertise turned into structured, client-ready products.',
      'Clinical inputs converted into clear diet frameworks and program-based plans.',
      'Nutrition systems adapted to US lifestyle — food availability, seasons, and routines.',
      'A premium, scalable nutrition system with program tiers and consultation flows.',
      'A CSS framework standardising tone, clarity, and premium advisory positioning.',
    ],
    metrics: [],
    exhibits: [
      { src: '/work/one-essence/01.jpg', w: 848, h: 1200, cap: 'One Essence — nutrition book cover' },
    ],
  },
];

export const getPillar = (slug) => PILLARS.find((p) => p.slug === slug);
export const getCase = (slug) => CASES.find((c) => c.slug === slug);
